#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThemeKind {
    One,
    Ayu,
    Gruvbox,
    Dracula,
    SolarizedLight,
    Everforest,
    Catppuccin,
    CatppuccinLatte,
    Ethereal,
    FlexokiLight,
    Hackerman,
    Kanagawa,
    MatteBlack,
    Miasma,
    Nord,
    OsakaJade,
    Ristretto,
    RosePine,
    TokyoNight,
    Vantablack,
    White,
    RetroboxClassic,
    TokyoNightDay,
    TokyoNightClassic,
    Zellner,
}

#[derive(Debug, Clone, Copy)]
pub struct ThemePalette {
    pub chrome_bg: u32,
    pub chrome_border: u32,
    pub app_bg: u32,
    pub sidebar_bg: u32,
    pub terminal_bg: u32,
    pub panel_bg: u32,
    pub panel_active_bg: u32,
    pub tab_bg: u32,
    pub tab_active_bg: u32,
    pub border: u32,
    pub text_primary: u32,
    pub text_muted: u32,
    pub text_disabled: u32,
    pub notice_bg: u32,
    pub notice_text: u32,
    pub accent: u32,
    pub terminal_cursor: u32,
    pub terminal_selection_bg: u32,
    pub terminal_selection_fg: u32,
}

impl ThemeKind {
    pub fn label(self) -> &'static str {
        match self {
            ThemeKind::One => "One Dark",
            ThemeKind::Ayu => "Ayu Dark",
            ThemeKind::Gruvbox => "Gruvbox Dark",
            ThemeKind::Dracula => "Dracula",
            ThemeKind::SolarizedLight => "Solarized Light",
            ThemeKind::Everforest => "Everforest",
            ThemeKind::Catppuccin => "Catppuccin",
            ThemeKind::CatppuccinLatte => "Catppuccin Latte",
            ThemeKind::Ethereal => "Ethereal",
            ThemeKind::FlexokiLight => "Flexoki Light",
            ThemeKind::Hackerman => "Hackerman",
            ThemeKind::Kanagawa => "Kanagawa",
            ThemeKind::MatteBlack => "Matte Black",
            ThemeKind::Miasma => "Miasma",
            ThemeKind::Nord => "Nord",
            ThemeKind::OsakaJade => "Osaka Jade",
            ThemeKind::Ristretto => "Ristretto",
            ThemeKind::RosePine => "Rose Pine",
            ThemeKind::TokyoNight => "Tokyo Night",
            ThemeKind::Vantablack => "Vantablack",
            ThemeKind::White => "White",
            ThemeKind::RetroboxClassic => "Retrobox Classic",
            ThemeKind::TokyoNightDay => "TokyoNight Day",
            ThemeKind::TokyoNightClassic => "TokyoNight Classic",
            ThemeKind::Zellner => "Zellner",
        }
    }

    pub fn palette(self) -> ThemePalette {
        match self {
            ThemeKind::One => ThemePalette {
                chrome_bg: 0x3b414d,
                chrome_border: 0x464b57,
                app_bg: 0x282c33,
                sidebar_bg: 0x2f343e,
                terminal_bg: 0x282c34,
                panel_bg: 0x2e343e,
                panel_active_bg: 0x363c46,
                tab_bg: 0x2f343e,
                tab_active_bg: 0x282c33,
                border: 0x363c46,
                text_primary: 0xc8ccd4,
                text_muted: 0x838994,
                text_disabled: 0x696b77,
                notice_bg: 0x5d3330,
                notice_text: 0xffe3dc,
                accent: 0x74ade8,
                terminal_cursor: 0xebdbb2,
                terminal_selection_bg: 0x3e4451,
                terminal_selection_fg: 0xc8ccd4,
            },
            ThemeKind::Ayu => ThemePalette {
                chrome_bg: 0x313337,
                chrome_border: 0x3f4043,
                app_bg: 0x0d1016,
                sidebar_bg: 0x1f2127,
                terminal_bg: 0x0d1016,
                panel_bg: 0x1f2127,
                panel_active_bg: 0x2a2d34,
                tab_bg: 0x1f2127,
                tab_active_bg: 0x0d1016,
                border: 0x3f4043,
                text_primary: 0xbfbdb6,
                text_muted: 0x8a8986,
                text_disabled: 0x6f6e6b,
                notice_bg: 0x5d3330,
                notice_text: 0xffe3dc,
                accent: 0x5ac1fe,
                terminal_cursor: 0xbfbdb6,
                terminal_selection_bg: 0x2f3f53,
                terminal_selection_fg: 0xd9d7cf,
            },
            ThemeKind::Gruvbox => ThemePalette {
                chrome_bg: 0x3c3836,
                chrome_border: 0x504945,
                app_bg: 0x282828,
                sidebar_bg: 0x32302f,
                terminal_bg: 0x282828,
                panel_bg: 0x32302f,
                panel_active_bg: 0x3c3836,
                tab_bg: 0x32302f,
                tab_active_bg: 0x282828,
                border: 0x504945,
                text_primary: 0xebdbb2,
                text_muted: 0xa89984,
                text_disabled: 0x928374,
                notice_bg: 0x5d3330,
                notice_text: 0xffe3dc,
                accent: 0x83a598,
                terminal_cursor: 0xebdbb2,
                terminal_selection_bg: 0x504945,
                terminal_selection_fg: 0xebdbb2,
            },
            ThemeKind::Dracula => ThemePalette {
                chrome_bg: 0x343746,
                chrome_border: 0x44475a,
                app_bg: 0x282a36,
                sidebar_bg: 0x2d2f3f,
                terminal_bg: 0x282a36,
                panel_bg: 0x2d2f3f,
                panel_active_bg: 0x3a3d52,
                tab_bg: 0x2d2f3f,
                tab_active_bg: 0x282a36,
                border: 0x44475a,
                text_primary: 0xf8f8f2,
                text_muted: 0x9ea0b0,
                text_disabled: 0x6272a4,
                notice_bg: 0x55304a,
                notice_text: 0xffe4f0,
                accent: 0xbd93f9,
                terminal_cursor: 0xf8f8f2,
                terminal_selection_bg: 0x44475a,
                terminal_selection_fg: 0xf8f8f2,
            },
            ThemeKind::SolarizedLight => ThemePalette {
                chrome_bg: 0xeee8d5,
                chrome_border: 0xd8cfba,
                app_bg: 0xfdf6e3,
                sidebar_bg: 0xf6efdc,
                terminal_bg: 0xfdf6e3,
                panel_bg: 0xf6efdc,
                panel_active_bg: 0xeee8d5,
                tab_bg: 0xeee8d5,
                tab_active_bg: 0xfdf6e3,
                border: 0xd8cfba,
                text_primary: 0x586e75,
                text_muted: 0x93a1a1,
                text_disabled: 0xaeb9b7,
                notice_bg: 0xf7dbd3,
                notice_text: 0x8f3b2f,
                accent: 0x268bd2,
                terminal_cursor: 0x586e75,
                terminal_selection_bg: 0xeee8d5,
                terminal_selection_fg: 0x073642,
            },
            ThemeKind::Everforest => ThemePalette {
                chrome_bg: 0x343f44,
                chrome_border: 0x4a555b,
                app_bg: 0x2d353b,
                sidebar_bg: 0x343f44,
                terminal_bg: 0x2d353b,
                panel_bg: 0x343f44,
                panel_active_bg: 0x3d484d,
                tab_bg: 0x343f44,
                tab_active_bg: 0x2d353b,
                border: 0x4a555b,
                text_primary: 0xd3c6aa,
                text_muted: 0x9da9a0,
                text_disabled: 0x7a8478,
                notice_bg: 0x5a3a3d,
                notice_text: 0xf6e7d1,
                accent: 0x7fbbb3,
                terminal_cursor: 0xd3c6aa,
                terminal_selection_bg: 0x4a555b,
                terminal_selection_fg: 0xd3c6aa,
            },
            ThemeKind::Catppuccin => ThemePalette {
                chrome_bg: 0x181825,
                chrome_border: 0x313244,
                app_bg: 0x1e1e2e,
                sidebar_bg: 0x181825,
                terminal_bg: 0x1e1e2e,
                panel_bg: 0x313244,
                panel_active_bg: 0x45475a,
                tab_bg: 0x313244,
                tab_active_bg: 0x1e1e2e,
                border: 0x45475a,
                text_primary: 0xcdd6f4,
                text_muted: 0xa6adc8,
                text_disabled: 0x6c7086,
                notice_bg: 0xf38ba8,
                notice_text: 0x1e1e2e,
                accent: 0x89b4fa,
                terminal_cursor: 0xf5e0dc,
                terminal_selection_bg: 0xf5e0dc,
                terminal_selection_fg: 0x1e1e2e,
            },
            ThemeKind::CatppuccinLatte => ThemePalette {
                chrome_bg: 0xe6e9ef,
                chrome_border: 0xccd0da,
                app_bg: 0xeff1f5,
                sidebar_bg: 0xe6e9ef,
                terminal_bg: 0xeff1f5,
                panel_bg: 0xe6e9ef,
                panel_active_bg: 0xdce0e8,
                tab_bg: 0xe6e9ef,
                tab_active_bg: 0xeff1f5,
                border: 0xccd0da,
                text_primary: 0x4c4f69,
                text_muted: 0x7c7f93,
                text_disabled: 0x9ca0b0,
                notice_bg: 0xd20f39,
                notice_text: 0xeff1f5,
                accent: 0x1e66f5,
                terminal_cursor: 0xdc8a78,
                terminal_selection_bg: 0xdc8a78,
                terminal_selection_fg: 0xeff1f5,
            },
            ThemeKind::Ethereal => ThemePalette {
                chrome_bg: 0x060b1e,
                chrome_border: 0x2a355d,
                app_bg: 0x060b1e,
                sidebar_bg: 0x10162a,
                terminal_bg: 0x060b1e,
                panel_bg: 0x10162a,
                panel_active_bg: 0x1a2340,
                tab_bg: 0x10162a,
                tab_active_bg: 0x060b1e,
                border: 0x2a355d,
                text_primary: 0xffcead,
                text_muted: 0x9aa6d6,
                text_disabled: 0x6d7db6,
                notice_bg: 0xed5b5a,
                notice_text: 0x060b1e,
                accent: 0x7d82d9,
                terminal_cursor: 0xffcead,
                terminal_selection_bg: 0xffcead,
                terminal_selection_fg: 0x060b1e,
            },
            ThemeKind::FlexokiLight => ThemePalette {
                chrome_bg: 0xf2f0e5,
                chrome_border: 0xdad8ce,
                app_bg: 0xfffcf0,
                sidebar_bg: 0xf8f5ea,
                terminal_bg: 0xfffcf0,
                panel_bg: 0xf8f5ea,
                panel_active_bg: 0xeee9d8,
                tab_bg: 0xf8f5ea,
                tab_active_bg: 0xfffcf0,
                border: 0xdad8ce,
                text_primary: 0x100f0f,
                text_muted: 0x6f6b5e,
                text_disabled: 0x9a9689,
                notice_bg: 0xd14d41,
                notice_text: 0xfffcf0,
                accent: 0x205ea6,
                terminal_cursor: 0x100f0f,
                terminal_selection_bg: 0xcecdc3,
                terminal_selection_fg: 0x100f0f,
            },
            ThemeKind::Hackerman => ThemePalette {
                chrome_bg: 0x10131f,
                chrome_border: 0x29334d,
                app_bg: 0x0b0c16,
                sidebar_bg: 0x131a2a,
                terminal_bg: 0x0b0c16,
                panel_bg: 0x1a2033,
                panel_active_bg: 0x26304a,
                tab_bg: 0x1a2033,
                tab_active_bg: 0x0b0c16,
                border: 0x29334d,
                text_primary: 0xddf7ff,
                text_muted: 0x90a2c9,
                text_disabled: 0x6a6e95,
                notice_bg: 0x50f872,
                notice_text: 0x0b0c16,
                accent: 0x82fb9c,
                terminal_cursor: 0xddf7ff,
                terminal_selection_bg: 0xddf7ff,
                terminal_selection_fg: 0x0b0c16,
            },
            ThemeKind::Kanagawa => ThemePalette {
                chrome_bg: 0x1f1f28,
                chrome_border: 0x363646,
                app_bg: 0x1f1f28,
                sidebar_bg: 0x16161d,
                terminal_bg: 0x1f1f28,
                panel_bg: 0x2a2a37,
                panel_active_bg: 0x363646,
                tab_bg: 0x2a2a37,
                tab_active_bg: 0x1f1f28,
                border: 0x727169,
                text_primary: 0xdcd7ba,
                text_muted: 0xa6a69c,
                text_disabled: 0x727169,
                notice_bg: 0xc34043,
                notice_text: 0x1f1f28,
                accent: 0x7e9cd8,
                terminal_cursor: 0xc8c093,
                terminal_selection_bg: 0x2d4f67,
                terminal_selection_fg: 0xc8c093,
            },
            ThemeKind::MatteBlack => ThemePalette {
                chrome_bg: 0x1a1a1a,
                chrome_border: 0x333333,
                app_bg: 0x121212,
                sidebar_bg: 0x1a1a1a,
                terminal_bg: 0x121212,
                panel_bg: 0x1f1f1f,
                panel_active_bg: 0x2a2a2a,
                tab_bg: 0x1f1f1f,
                tab_active_bg: 0x121212,
                border: 0x333333,
                text_primary: 0xbebebe,
                text_muted: 0x8a8a8d,
                text_disabled: 0x666666,
                notice_bg: 0xd35f5f,
                notice_text: 0x121212,
                accent: 0xe68e0d,
                terminal_cursor: 0xeaeaea,
                terminal_selection_bg: 0x333333,
                terminal_selection_fg: 0xbebebe,
            },
            ThemeKind::Miasma => ThemePalette {
                chrome_bg: 0x1a1a1a,
                chrome_border: 0x3a3a3a,
                app_bg: 0x222222,
                sidebar_bg: 0x262626,
                terminal_bg: 0x222222,
                panel_bg: 0x2b2b2b,
                panel_active_bg: 0x333333,
                tab_bg: 0x2b2b2b,
                tab_active_bg: 0x222222,
                border: 0x3a3a3a,
                text_primary: 0xc2c2b0,
                text_muted: 0x948a8b,
                text_disabled: 0x666666,
                notice_bg: 0x685742,
                notice_text: 0xf1e5e7,
                accent: 0x78824b,
                terminal_cursor: 0xc7c7c7,
                terminal_selection_bg: 0x78824b,
                terminal_selection_fg: 0xc2c2b0,
            },
            ThemeKind::Nord => ThemePalette {
                chrome_bg: 0x3b4252,
                chrome_border: 0x4c566a,
                app_bg: 0x2e3440,
                sidebar_bg: 0x3b4252,
                terminal_bg: 0x2e3440,
                panel_bg: 0x434c5e,
                panel_active_bg: 0x4c566a,
                tab_bg: 0x434c5e,
                tab_active_bg: 0x2e3440,
                border: 0x4c566a,
                text_primary: 0xd8dee9,
                text_muted: 0xa7b5cc,
                text_disabled: 0x4c566a,
                notice_bg: 0xbf616a,
                notice_text: 0xeceff4,
                accent: 0x81a1c1,
                terminal_cursor: 0xd8dee9,
                terminal_selection_bg: 0x4c566a,
                terminal_selection_fg: 0xd8dee9,
            },
            ThemeKind::OsakaJade => ThemePalette {
                chrome_bg: 0x192b23,
                chrome_border: 0x23372b,
                app_bg: 0x111c18,
                sidebar_bg: 0x192b23,
                terminal_bg: 0x111c18,
                panel_bg: 0x1e3027,
                panel_active_bg: 0x2a4136,
                tab_bg: 0x1e3027,
                tab_active_bg: 0x111c18,
                border: 0x53685b,
                text_primary: 0xc1c497,
                text_muted: 0x9fb09f,
                text_disabled: 0x53685b,
                notice_bg: 0xff5345,
                notice_text: 0x111c18,
                accent: 0x509475,
                terminal_cursor: 0xd7c995,
                terminal_selection_bg: 0xc1c497,
                terminal_selection_fg: 0x111c18,
            },
            ThemeKind::Ristretto => ThemePalette {
                chrome_bg: 0x322a2b,
                chrome_border: 0x534949,
                app_bg: 0x2c2525,
                sidebar_bg: 0x322a2b,
                terminal_bg: 0x2c2525,
                panel_bg: 0x3a3233,
                panel_active_bg: 0x474041,
                tab_bg: 0x3a3233,
                tab_active_bg: 0x2c2525,
                border: 0x534949,
                text_primary: 0xe6d9db,
                text_muted: 0xb8aeb0,
                text_disabled: 0x948a8b,
                notice_bg: 0xfd6883,
                notice_text: 0x2c2525,
                accent: 0xf38d70,
                terminal_cursor: 0xc3b7b8,
                terminal_selection_bg: 0x403e41,
                terminal_selection_fg: 0xe6d9db,
            },
            ThemeKind::RosePine => ThemePalette {
                chrome_bg: 0xf2e9e1,
                chrome_border: 0xdfdad9,
                app_bg: 0xfaf4ed,
                sidebar_bg: 0xf2e9e1,
                terminal_bg: 0xfaf4ed,
                panel_bg: 0xf2e9e1,
                panel_active_bg: 0xe8e0d8,
                tab_bg: 0xf2e9e1,
                tab_active_bg: 0xfaf4ed,
                border: 0xdfdad9,
                text_primary: 0x575279,
                text_muted: 0x797593,
                text_disabled: 0x9893a5,
                notice_bg: 0xb4637a,
                notice_text: 0xfaf4ed,
                accent: 0x56949f,
                terminal_cursor: 0xcecacd,
                terminal_selection_bg: 0xdfdad9,
                terminal_selection_fg: 0x575279,
            },
            ThemeKind::TokyoNight => ThemePalette {
                chrome_bg: 0x32344a,
                chrome_border: 0x444b6a,
                app_bg: 0x1a1b26,
                sidebar_bg: 0x32344a,
                terminal_bg: 0x1a1b26,
                panel_bg: 0x32344a,
                panel_active_bg: 0x444b6a,
                tab_bg: 0x32344a,
                tab_active_bg: 0x1a1b26,
                border: 0x444b6a,
                text_primary: 0xa9b1d6,
                text_muted: 0xacb0d0,
                text_disabled: 0x787c99,
                notice_bg: 0xf7768e,
                notice_text: 0x1a1b26,
                accent: 0x7aa2f7,
                terminal_cursor: 0xc0caf5,
                terminal_selection_bg: 0x7aa2f7,
                terminal_selection_fg: 0xc0caf5,
            },
            ThemeKind::Vantablack => ThemePalette {
                chrome_bg: 0x0d0d0d,
                chrome_border: 0x2a2a2a,
                app_bg: 0x0d0d0d,
                sidebar_bg: 0x121212,
                terminal_bg: 0x0d0d0d,
                panel_bg: 0x121212,
                panel_active_bg: 0x1a1a1a,
                tab_bg: 0x121212,
                tab_active_bg: 0x0d0d0d,
                border: 0x2a2a2a,
                text_primary: 0xffffff,
                text_muted: 0xb3b3b3,
                text_disabled: 0x7a7a7a,
                notice_bg: 0xa4a4a4,
                notice_text: 0x0d0d0d,
                accent: 0x8d8d8d,
                terminal_cursor: 0xffffff,
                terminal_selection_bg: 0xffffff,
                terminal_selection_fg: 0x0d0d0d,
            },
            ThemeKind::White => ThemePalette {
                chrome_bg: 0xf5f5f5,
                chrome_border: 0xd9d9d9,
                app_bg: 0xffffff,
                sidebar_bg: 0xf7f7f7,
                terminal_bg: 0xffffff,
                panel_bg: 0xf7f7f7,
                panel_active_bg: 0xebebeb,
                tab_bg: 0xf7f7f7,
                tab_active_bg: 0xffffff,
                border: 0xd9d9d9,
                text_primary: 0x000000,
                text_muted: 0x6e6e6e,
                text_disabled: 0xc0c0c0,
                notice_bg: 0x2a2a2a,
                notice_text: 0xffffff,
                accent: 0x6e6e6e,
                terminal_cursor: 0x000000,
                terminal_selection_bg: 0x1a1a1a,
                terminal_selection_fg: 0xffffff,
            },
            ThemeKind::RetroboxClassic => ThemePalette {
                chrome_bg: 0x2a241f,
                chrome_border: 0x4d4339,
                app_bg: 0x1f1a17,
                sidebar_bg: 0x26211d,
                terminal_bg: 0x1b1815,
                panel_bg: 0x26211d,
                panel_active_bg: 0x312a23,
                tab_bg: 0x26211d,
                tab_active_bg: 0x1f1a17,
                border: 0x4d4339,
                text_primary: 0xf2d7b6,
                text_muted: 0xc1a98f,
                text_disabled: 0x8e7966,
                notice_bg: 0x6a3d32,
                notice_text: 0xffe9dd,
                accent: 0xf4a261,
                terminal_cursor: 0xf2d7b6,
                terminal_selection_bg: 0x4d4339,
                terminal_selection_fg: 0xf2d7b6,
            },
            ThemeKind::TokyoNightDay => ThemePalette {
                chrome_bg: 0xd5d6db,
                chrome_border: 0xc4c8da,
                app_bg: 0xe1e2e7,
                sidebar_bg: 0xd5d6db,
                terminal_bg: 0xe1e2e7,
                panel_bg: 0xd5d6db,
                panel_active_bg: 0xc4c8da,
                tab_bg: 0xd5d6db,
                tab_active_bg: 0xe1e2e7,
                border: 0xc4c8da,
                text_primary: 0x3760bf,
                text_muted: 0x6172b0,
                text_disabled: 0x8990b3,
                notice_bg: 0xf2d9df,
                notice_text: 0x8c4351,
                accent: 0x2e7de9,
                terminal_cursor: 0x3760bf,
                terminal_selection_bg: 0xc4c8da,
                terminal_selection_fg: 0x1a1b26,
            },
            ThemeKind::TokyoNightClassic => ThemePalette {
                chrome_bg: 0x1f2335,
                chrome_border: 0x292e42,
                app_bg: 0x1a1b26,
                sidebar_bg: 0x1f2335,
                terminal_bg: 0x1a1b26,
                panel_bg: 0x1f2335,
                panel_active_bg: 0x292e42,
                tab_bg: 0x1f2335,
                tab_active_bg: 0x1a1b26,
                border: 0x292e42,
                text_primary: 0xc0caf5,
                text_muted: 0x9aa5ce,
                text_disabled: 0x6b7191,
                notice_bg: 0x51324a,
                notice_text: 0xf9e2f1,
                accent: 0x7aa2f7,
                terminal_cursor: 0xc0caf5,
                terminal_selection_bg: 0x364a82,
                terminal_selection_fg: 0xc0caf5,
            },
            ThemeKind::Zellner => ThemePalette {
                chrome_bg: 0xf0f0f0,
                chrome_border: 0xd9d9d9,
                app_bg: 0xffffff,
                sidebar_bg: 0xf7f7f7,
                terminal_bg: 0xffffff,
                panel_bg: 0xf7f7f7,
                panel_active_bg: 0xebebeb,
                tab_bg: 0xf7f7f7,
                tab_active_bg: 0xffffff,
                border: 0xd9d9d9,
                text_primary: 0x303030,
                text_muted: 0x6e6e6e,
                text_disabled: 0x9c9c9c,
                notice_bg: 0xf5d7dc,
                notice_text: 0x8a1f2d,
                accent: 0x005faf,
                terminal_cursor: 0x303030,
                terminal_selection_bg: 0xdbeafe,
                terminal_selection_fg: 0x111111,
            },
        }
    }
}
