name: CodSpeed

on:
  push:
    branches: [main]
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
  CARGO_TERM_COLOR: always
  NIGHTLY_TOOLCHAIN: nightly-2025-11-30

jobs:
  codspeed:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
      - uses: taiki-e/install-action@a7c938ee233ac44ef6f2fba5ac2d30fa12584c6e # cargo-codspeed
        with:
          tool: cargo-codspeed
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libavahi-client-dev
      - name: Build the benchmark target(s)
        run: cargo codspeed build -p arbor-core -m simulation
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@281164b0f014a4e7badd2c02cecad9b595b70537 # v4.11.1
        with:
          mode: simulation
          run: cargo codspeed run
